Display Contents of CSV file on template
DSpeichert/cloudvcl pull request #22
Opened 2017-04-17 17:04 UTC by syavatkar

Display contents of CSV file. Once csv file is selected on the form, the parsed contents of the csv file will be displayed on the template.

2017-04-17 20:25 UTC, DSpeichert requested changes

2017-04-17 20:25 UTC, DSpeichert commented on cvcl/forms.py
> +class UploadFileForm(forms.Form):
Name too generic

2017-04-17 20:25 UTC, DSpeichert commented on cloudvcl/settings.py
> +# Location on the hard drive where we want files uploaded to
Isn't that the default? Anyway, it's not relevant because we don't save nor serve those uploaded.
Remove

2017-04-17 20:25 UTC, DSpeichert commented on cvcl/templates/fileUpload.html
> +            {{ form.as_table }}
https://django-bootstrap3.readthedocs.io/en/latest/templatetags.html#bootstrap-form

2017-04-17 20:25 UTC, DSpeichert commented on cvcl/templates/fileUpload.html
> +        <table>
Add bootstrap styling:
https://getbootstrap.com/css/#tables

2017-04-17 20:25 UTC, DSpeichert commented on cvcl/urls.py
> +                  url(r'^upload/', addreport, name='csv_upload'),
* Bad URL (make it context-relevant)
* random view function name (make it a class too)
* "csv_upload" is also random, change to follow our style
* You added whitespaces

2017-04-17 20:25 UTC, DSpeichert commented on cvcl/views/csvformView.py
> +    return render(request, 'fileUpload.html', {'form': form})
template name is copy-pasta from some tutorial, make it specific to our case

2017-04-17 20:25 UTC, DSpeichert commented on cvcl/views/csvformView.py
> +            # reader = csv.reader(form.cleaned_data['file'])
Don't commit crap that's commented out

2017-04-17 21:11 UTC, syavatkar commented on cloudvcl/settings.py
> +# Location on the hard drive where we want files uploaded to
Yeah it is . I had it temporarily but the form does not store it there anyways.

2017-04-17 21:41 UTC, DSpeichert commented on cloudvcl/settings.py
> +# Location on the hard drive where we want files uploaded to
So remove it.

2017-04-20 01:29 UTC, DSpeichert requested changes

2017-04-20 01:29 UTC, DSpeichert commented on cloudvcl/settings.py
> +# # Location on the hard drive where we want files uploaded to
It doesn't look removed to me

2017-04-20 01:29 UTC, DSpeichert commented on cvcl/forms.py
> +# from django.contrib.auth.models import User
What is this for

2017-04-20 01:29 UTC, DSpeichert commented on cvcl/forms.py
> +            email2 = user['Username'] + "@drexel.edu"
Why is this called email2?

2017-04-20 01:29 UTC, DSpeichert commented on cvcl/forms.py
> +            User.objects.create_user(user['Username'], email=email2, first_name=user['First Name'],
What if such a user already exists?

2017-04-20 01:29 UTC, DSpeichert commented on cvcl/templates/fileUpload.html
> +            {{ form }}
This should be `{% bootstrap_form form %}`

2017-04-20 01:29 UTC, DSpeichert commented on cvcl/forms.py
> +            User.objects.create_user(user['Username'], email=email2, first_name=user['First Name'],
You're creating users but you're not adding them to the class

2017-04-20 01:29 UTC, DSpeichert commented on cvcl/urls.py
> +    url(r'^add_students/', DataView.as_view(), name='csv_upload'),
Bad URL and bad name, already explained that

2017-04-20 01:29 UTC, DSpeichert commented on cvcl/urls.py
> +from cvcl.views.csvformView import *
This is wrong, you should edit views/__init__.py instead

2017-04-20 02:10 UTC, syavatkar commented on cloudvcl/settings.py
> +# # Location on the hard drive where we want files uploaded to
I removed it from my settings.py file. Yet for some reason it still shows the previous settings.py file

2017-04-20 02:11 UTC, syavatkar commented on cvcl/forms.py
> +# from django.contrib.auth.models import User
I will remove the comment. I realized we didn't need it earlier when our User model inherits from django.contrib.auth.models.User

2017-04-20 23:52 UTC, DSpeichert requested changes

2017-04-20 23:52 UTC, DSpeichert commented on cvcl/forms.py
> +                raise forms.ValidationError(u'Username "%s" already exists' % username)
So you're throwing an error just because the user exists in the database? No way to add him/her to course, huh?

2017-04-20 23:52 UTC, DSpeichert commented on cvcl/forms.py
> +                                         last_name=user['Last Name'])
Still not adding the user to course

2017-04-20 23:52 UTC, DSpeichert commented on cvcl/urls.py
> +    url(r'^courses/add_students/', DataView.as_view(), name='csv_upload'),
Still wrong. Bad class name, bad view name.

2017-04-24 05:47 UTC, DSpeichert requested changes

2017-04-24 05:47 UTC, DSpeichert commented on cvcl/urls.py
> +from cvcl.views.courseUser import *
Not the way it should be done, I said before how to do it

2017-04-24 05:47 UTC, DSpeichert commented on cvcl/urls.py
> +    url(r'^courses/(?P<pk>\d+)/deleteStudent/(?P<user_pk>\d+)', RemoveStudent.as_view(), name='delete_user'),
So you use `deleteStudent`, `RemoveStudent` and `delete_user` as 3 different names for a single thing in one line?

2017-04-24 05:47 UTC, DSpeichert commented on cvcl/views/course.py
> +        return Course.objects.filter(instructor=self.request.user)
don't edit EOL on last line

2017-04-24 05:47 UTC, DSpeichert commented on cvcl/templates/fileUpload.html
> +{% endblock %}
add EOL

2017-04-24 05:47 UTC, DSpeichert commented on cvcl/forms.py
> +            courseID = user['Child Course ID']
where do you use that?

2017-04-24 05:47 UTC, DSpeichert commented on cvcl/views/courseUser.py
> +class RemoveStudent(DeleteView):
So anyone can remove anyone from any course? How convenient.

2017-04-24 05:47 UTC, DSpeichert commented on cvcl/views/csvformView.py
> +    success_url = '/add_students'
Is this correct?

2017-04-24 05:47 UTC, DSpeichert commented on cvcl/views/csvformView.py
> +class DataView(FormView):
Bad class name, bad filename too

2017-04-24 13:40 UTC, syavatkar commented on cvcl/views/course.py
> +        return Course.objects.filter(instructor=self.request.user)
What do you mean don't edit end of line? The spacing?

2017-04-24 13:40 UTC, syavatkar commented on cvcl/templates/fileUpload.html
> +{% endblock %}
add end of line?

2017-04-24 14:59 UTC, DSpeichert commented on cvcl/views/course.py
> +        return Course.objects.filter(instructor=self.request.user)
See your detailed diff. You removed "newline" from end of file. Don't do that, all files should end with a newline.

2017-04-24 14:59 UTC, DSpeichert commented on cvcl/templates/fileUpload.html
> +{% endblock %}
All files should end with a newline.

2017-04-24 16:53 UTC, DSpeichert requested changes

2017-04-24 16:53 UTC, DSpeichert commented on cvcl/forms.py
> +from .models import Assignment, VmDefinition, User
Why did you change that now?

2017-04-24 16:53 UTC, DSpeichert commented on cvcl/forms.py
>              email = user['Username'] + "@drexel.edu"
Do not hardcode domain, it should be configurable in settings.py. Otherwise, it's useless outside Drexel.

2017-04-24 16:53 UTC, DSpeichert commented on cvcl/templates/course_detail.html
> +                            <form action="{% url 'delete_student' user_pk=student.pk pk=course.pk %}" method="post">
This name is not entirely correct because you're not completely deleting a student.

2017-04-24 16:53 UTC, DSpeichert commented on cvcl/views/AddUser.py
> +        return '/courses/{0}'.format(self.kwargs['pk'])
This is horrible practice.
Read documentation.
https://github.com/DSpeichert/cloudvcl/blob/master/cvcl/views/environment.py#L57-L58

2017-04-24 16:53 UTC, DSpeichert commented on cvcl/views/__init__.py
> +from .AddUser import *
You are mixing case-styles. Follow established pattern.

2017-04-24 21:43 UTC, DSpeichert commented
Update issue description, it doesn't reflect the work scope now.

2017-04-26 02:37 UTC, DSpeichert requested changes

2017-04-26 02:37 UTC, DSpeichert commented on cloudvcl/settings.py
> +# Drexel Domain
So you effectively tell everyone to put "drexel.edu" below? How is that making it configurable?
You must provide a clear description of what should be typically entered and how it is going to be used.

2017-04-26 02:37 UTC, DSpeichert commented on cvcl/forms.py
> +        for user1 in reader:
why "user1"?

2017-04-26 02:37 UTC, DSpeichert commented on cvcl/forms.py
> +            email = user1['Username'] + getattr(settings, "EMAIL_DOMAIN", None)
What if you get "None"?
`TypeError: Can't convert 'NoneType' object to str implicitly`

2017-04-26 02:37 UTC, DSpeichert commented on cvcl/forms.py
> +                # user.email = email
What is that for?

2017-04-26 02:37 UTC, DSpeichert commented on cvcl/views/AddUser.py
> +        course_id = self.kwargs['pk']
it could be one line

2017-04-26 15:59 UTC, DSpeichert requested changes
Fix it

2017-04-26 15:59 UTC, DSpeichert commented on cloudvcl/settings.py
> +# Assign email to users being added to database
Not a good description

2017-04-26 15:59 UTC, DSpeichert commented on cloudvcl/settings.py
> +
double spacing?

2017-04-26 15:59 UTC, DSpeichert commented on cvcl/forms.py
> +
why empty line?

2017-04-26 15:59 UTC, DSpeichert commented on cvcl/forms.py
> +            email = users['Username'] + getattr(settings, "EMAIL_DOMAIN", '@email.com')
The default here doesn't make any sense. Empty string would be better than sending it to a known arbitrary domain.

2017-04-26 15:59 UTC, DSpeichert commented on cvcl/urls.py
> +from django.conf.urls.static import static
Why did you add this?

2017-04-26 15:59 UTC, DSpeichert commented on cvcl/urls.py
> +from django.conf import settings
Why did you add this?

2017-04-26 15:59 UTC, DSpeichert commented on cvcl/urls.py
> +    url(r'^courses/(?P<pk>\d+)/add_students$', AddStudent.as_view(), name='csv_upload'),
make the `name` = `courses.add_students`
Class should be `CourseAddStudents`

2017-04-26 15:59 UTC, DSpeichert commented on cvcl/urls.py
> +    url(r'^courses/(?P<pk>\d+)/deleteStudent/(?P<user_pk>\d+)', DeleteStudent.as_view(), name='delete_student'),
This line should be moved to line 26. Why did you make the order random?
Also, URL should be lowercase. Change class name to follow pattern and name too.

2017-04-26 15:59 UTC, DSpeichert commented on cvcl/views/AddUser.py
> +@method_decorator(user_passes_test(is_instructor_check), name='dispatch')
Are you checking if the instructor is an instructor for this course?

2017-04-26 15:59 UTC, DSpeichert commented on cvcl/views/AddUser.py
> +    template_name = 'fileUpload.html'
Improve file name, nobody knows what file it's uploading just from the name.

2017-04-26 15:59 UTC, DSpeichert commented on cvcl/views/AddUser.py
> +from django.shortcuts import render
What is this for?

2017-04-26 15:59 UTC, DSpeichert commented on cvcl/views/AddUser.py
> +import io
What is this for?

2017-04-26 15:59 UTC, DSpeichert commented on cvcl/views/AddUser.py
> +import csv
What is this for?

2017-04-26 15:59 UTC, DSpeichert commented on cvcl/views/AddUser.py
> +from django.http import HttpResponseRedirect
What is this for?

2017-04-26 15:59 UTC, DSpeichert commented on cvcl/views/AddUser.py
> +from django.views.generic import FormView, DetailView, ListView, UpdateView
Why import all of them?

2017-04-26 15:59 UTC, DSpeichert commented on cvcl/views/courseUser.py
> +@method_decorator(user_passes_test(is_instructor_check), name='dispatch')
Not checking if user is instructor for this course.

2017-04-26 15:59 UTC, DSpeichert commented on cvcl/views/courseUser.py
> +from django.shortcuts import render
Seriously? importing one thing twice?
Go through the imports and remove the unused ones!

2017-04-26 18:30 UTC, syavatkar commented on cvcl/views/AddUser.py
> +@method_decorator(user_passes_test(is_instructor_check), name='dispatch')
@method_decorator(user_passes_test(is_instructor_check), name='dispatch') .This is what you used. in the course.py file That only checks if a user is an instructor but it doesn't check if the user is the instructor for the specific course

2017-04-26 18:33 UTC, syavatkar commented on cvcl/views/AddUser.py
> +@method_decorator(user_passes_test(is_instructor_check), name='dispatch')
def get_queryset(self):
        return Course.objects.filter(instructor=self.request.user)

2017-04-26 19:22 UTC, syavatkar commented on cvcl/views/AddUser.py
> +    template_name = 'fileUpload.html'
how about csvFileUpload or AddUser.html

2017-04-26 19:28 UTC, syavatkar commented on cvcl/views/AddUser.py
> +    template_name = 'fileUpload.html'
I will make it user_upload.html

2017-04-26 20:41 UTC, DSpeichert requested changes
Missing changes

2017-04-26 20:41 UTC, DSpeichert commented on cvcl/urls.py
> +
why extra line?

2017-04-26 20:41 UTC, DSpeichert commented on cvcl/views/course.py
> +        return Course.objects.filter(instructor=self.request.user)
Still didn't do this.

2017-04-27 02:58 UTC, DSpeichert commented on cvcl/urls.py
> +
Empty line

2017-04-27 03:33 UTC, DSpeichert commented on cvcl/templates/user_upload.html
> +{% endblock %}
Missing newline

2017-04-27 03:36 UTC, DSpeichert approved these changes

2017-04-27 03:43 UTC, merged