Minor design improvements
DSpeichert/cloudvcl pull request #37
Opened 2017-04-24 18:57 UTC by mitchfeldman

Added some hyperlinks to index.html, switched order of buttons in environment_definition_detail.html, added some padding to master.html (necessary for material theme), and added line breaks everywhere else

2017-04-24 19:04 UTC, DSpeichert requested changes

2017-04-24 19:04 UTC, DSpeichert commented on cvcl/templates/assignment_create.html
> +    <br>
That's not spacing, that's new line. You should add a margin on h1 instead, in CSS.

2017-04-24 19:42 UTC, DSpeichert requested changes
CSS should be in a CSS file, not inline.

2017-04-24 20:34 UTC, DSpeichert requested changes

2017-04-24 20:34 UTC, DSpeichert commented on cvcl/templates/master.html
> -    {% block title %}<title>Cloud VCL</title>{% endblock %}
Why did you remove that?

2017-04-24 20:34 UTC, DSpeichert commented on cvcl/templates/master.html
> +            <a class="navbar-brand" href="{% url 'index' %}" style="padding-top:15px;">Cloud VCL</a> <!-- Padding is necessary with material theme -->
To CSS.

2017-04-24 20:58 UTC, DSpeichert requested changes

2017-04-24 20:58 UTC, DSpeichert commented on cvcl/templates/master.html
> +
why?

2017-04-24 20:58 UTC, DSpeichert commented on cvcl/templates/master.html
> +            <a id="navbrand" class="navbar-brand" href="{% url 'index' %}">Cloud VCL</a> <!-- Padding is necessary with material theme -->
Is the navbar-brand class used anywhere else? Why not use it to identify the style?

2017-04-24 21:08 UTC, DSpeichert approved these changes

2017-04-24 21:33 UTC, abhishekvalanju commented
Redo please, the Assignment Details/Update pages look horrible as shown by the screenshot I provided. Also restore that column you deleted from Courses detail and Environment Definition Details

2017-04-24 21:45 UTC, mitchfeldman commented
Assignments_detail is out of scope for this, I overlooked it. I can create a separate issue for that.

If you can show me what you're seeing on your end with the columns that'd be great.

2017-04-25 02:22 UTC, DSpeichert requested changes

2017-04-25 02:22 UTC, DSpeichert commented on cvcl/static/style.css
> +#navbrand {
Delete this, it doesn't do anything.

2017-04-25 02:22 UTC, DSpeichert commented on cvcl/templates/assignment_create.html
> +{% endblock %}
Add new line at the end of file

2017-04-25 02:22 UTC, DSpeichert commented on cvcl/templates/index.html
> +            <li>Create course from <a href="{% url "courses" %}">Courses</a></li>
This is inline help text. Remove it from here. It shouldn't be visible to students either. Add this back where appropriate according to #40.

2017-04-25 02:22 UTC, DSpeichert commented on cvcl/templates/master.html
> +            <a id="navbrand" class="navbar-brand" href="{% url 'index' %}">Cloud VCL</a> <!-- Padding is necessary with material theme -->
Undo, not necessary.

2017-04-27 03:25 UTC, DSpeichert approved these changes

2017-04-27 03:26 UTC, abhishekvalanju approved these changes
Looks good

2017-04-27 03:26 UTC, abhishekvalanju commented on cvcl/templates/environment_definition_list.html
> -            <th>Actions</th>
Add this back in

2017-04-27 03:26 UTC, abhishekvalanju commented on cvcl/templates/environment_definition_list.html
> -                <td>
Add the <td> back

2017-04-27 03:28 UTC, merged