Cloud-init: install packages, add users, add groups, bash user script
DSpeichert/cloudvcl pull request #55
Opened 2017-04-29 23:02 UTC by Nuyb

2017-04-29 23:09 UTC, DSpeichert requested changes
Needs changes

2017-04-29 23:09 UTC, DSpeichert commented on cvcl/views/assignment.py
> +            if vmd.hostname:
Undo, this is already fixed in master.

2017-04-29 23:09 UTC, DSpeichert commented on cvcl/views/assignment.py
> +            if vmd.script_per_boot:
You can't do that. That would replace everything else. You must MIME-encode it.
https://cloudinit.readthedocs.io/en/latest/topics/format.html#mime-multi-part-archive

2017-04-29 23:09 UTC, DSpeichert commented on cvcl/views/assignment.py
> +            if vmd.script_per_instance:
Same thing.

2017-04-29 23:09 UTC, DSpeichert commented on cvcl/models.py
> +class UserScript(models.Model):
Why is this a new model? Those scripts could be fields in VmDefinition.

2017-04-29 23:09 UTC, DSpeichert commented on cvcl/models.py
> +class AddGroup(models.Model):
Why is the model called `AddGroup`? A group is a group, so it could be `UserGroup`. Don't put verbs in model names.

2017-04-29 23:09 UTC, DSpeichert commented on cvcl/models.py
> +class InstallPackage(models.Model):
No verbs in model class names

2017-04-29 23:09 UTC, DSpeichert commented on cvcl/models.py
> +class AddUser(models.Model):
No verbs in model class names

2017-04-29 23:09 UTC, DSpeichert commented on cvcl/models.py
> +    package_update = models.BooleanField(default=False)
Why is package_update set for every package? It's independent of the packages you install.

2017-04-29 23:09 UTC, DSpeichert commented on cvcl/models.py
> +    package_upgrade = models.BooleanField(default=False)
Why is package_upgrade set for every package? It's independent of the packages you install.

2017-04-29 23:09 UTC, DSpeichert commented on cvcl/models.py
> +    package_reboot_if_required = models.BooleanField(default=False)
Why is package_reboot_if_required set for every package? It's independent of the packages you install.

2017-04-29 23:50 UTC, syavatkar commented on cvcl/models.py
> +    package_update = models.BooleanField(default=False)
@DSpeichert  Wouldn't it be better to create another model with the fields for package_update, package_upgrade, and package_reboot_if_required and create a relationship with this new model and the model we have for installing Packages.

2017-04-29 23:52 UTC, syavatkar commented on cvcl/models.py
> +class AddUser(models.Model):
can we just refer to the model name as Packages?

2017-04-29 23:52 UTC, DSpeichert commented on cvcl/models.py
> +    package_update = models.BooleanField(default=False)
Why would that be better?

2017-04-29 23:55 UTC, DSpeichert commented on cvcl/models.py
> +class AddUser(models.Model):
Not really, Model is a singular thing, must have a singular name. `Package` could work.

2017-04-30 00:00 UTC, syavatkar commented on cvcl/views/assignment.py
> +            if vmd.script_per_boot:
oh base64.encode right? This is similar as to what you were doing last term.

2017-04-30 00:03 UTC, syavatkar commented on cvcl/views/assignment.py
> +            if vmd.script_per_boot:
base64.b64encode(bytes(user_data, 'utf-8')).decode('utf-8')

2017-04-30 00:19 UTC, DSpeichert commented on cvcl/views/assignment.py
> +            if vmd.script_per_boot:
The code is literally there: https://cloudinit.readthedocs.io/en/latest/topics/format.html#helper-script-to-generate-mime-messages

2017-04-30 06:55 UTC, syavatkar commented on cvcl/models.py
> +    package_update = models.BooleanField(default=False)
"This module allows packages to be updated, upgraded or installed during boot. If any packages are to be installed or an upgrade is to be performed then the package cache will be updated first. " If this is being applied to all packages .Why not have a parent package class and a child package class that inherits those properties

2017-04-30 07:01 UTC, syavatkar commented on cvcl/views/assignment.py
> +            if vmd.script_per_boot:
found this one on django snippets. https://djangosnippets.org/snippets/3039/

2017-04-30 13:49 UTC, syavatkar commented on cvcl/views/assignment.py
> +            if vmd.script_per_boot:
The link your provided. Isn't it reading from a file? I am a bit confused. Are we having a file field in the form or are we taking in the user_data scripts that are pasted into the fields and encoding them into MIME format.

2017-05-04 03:10 UTC, closed without merging