2nd Draft of Instructor Documentation
DSpeichert/cloudvcl pull request #74
Opened 2017-05-06 04:10 UTC by Nuyb

Changed documentation format from CRUD to use cases.

2017-05-06 13:51 UTC, DSpeichert requested changes
Work more on this, my comments do not point out everything that is wrong with that.

2017-05-06 13:51 UTC, DSpeichert commented on documentation/docs/instructor.md
> +Set a hostname that will replace the hostname generated by default.
Explain the format of hostname generated by default.

2017-05-06 13:51 UTC, DSpeichert commented on documentation/docs/instructor.md
> +America/New_York
Give more examples and link to a list of all time zones.

2017-05-06 13:51 UTC, DSpeichert commented on documentation/docs/instructor.md
> +Sets the password for default user (username is OS-dependant). Leave blank to disable.
Link to documentation showing what is the username.
https://docs.cci.drexel.edu/display/cloud/Supported+Images (don't link to that page)

2017-05-06 13:51 UTC, DSpeichert commented on documentation/docs/instructor.md
> +SSH public key for default user (username is OS-dependant).
What is a default user?

2017-05-06 13:51 UTC, DSpeichert commented on documentation/docs/instructor.md
> +ssh-rsa AAAB... user@host
It's not a full example, give examples of multiple types of public keys. Full ones, the dots are obviously standing for majority of characters.

2017-05-06 13:51 UTC, DSpeichert commented on documentation/docs/instructor.md
> +#ps1_sysnative
What language will that be?

2017-05-06 13:51 UTC, DSpeichert commented on documentation/docs/instructor.md
> +Select the type of flavor: 01c-01m-10d reads 1 VCPU, 1 RAM GB, and 10 GB Total/Root Disk.
That's wrong, this only applies to our cloud, other clouds may have completely different flavors and flavor names.

2017-05-06 13:51 UTC, DSpeichert commented on documentation/docs/instructor.md
> +Choose the type of image you wish to use: CentOS 7.3, Ubuntu Server 16.04.2, Windows Server 2012 R2
This is horribly wrong again, there is no guarantee such images exist.

2017-05-06 13:51 UTC, DSpeichert commented on documentation/docs/instructor.md
> +`Reminder: The format of the CSV file used by Blackboard Learn may have additional fields; however, Cloud VCL only requires (Last Name, First Name, Username)`.
GENERATED not used by BB Learn. WE use it!

2017-05-06 13:51 UTC, DSpeichert commented on documentation/docs/instructor.md
> +`Please note: CTRL+C/CTRL+V doesn't work in this console.`
What else doesn't work? What is CTRL+C/CTRL+V?

2017-05-07 20:34 UTC, abhishekvalanju commented on documentation/docs/instructor.md
> +Navigate to https://cloudvcl.cci.drexel.edu/ and log in using your Drexel credentials. You will know that you've successfully logged in when you see `Logged in as YourUsername` in the top right corne
Again, make this non-Drexel specific. Say instead, log in using your institution's credentials

2017-05-08 01:32 UTC, Nuyb commented on documentation/docs/instructor.md
> +`Please note: CTRL+C/CTRL+V doesn't work in this console.`
i'm not sure about what else doesn't work here

2017-05-08 02:02 UTC, DSpeichert commented on documentation/docs/instructor.md
> +`Please note: CTRL+C/CTRL+V doesn't work in this console.`
It's easier to say what works. Keyboard, Video, Mouse. Hence the name is KVM. So audio won't work.

2017-05-08 02:13 UTC, closed without merging